In [1]:
# Data wrangling
import pandas as pd

# Numerical operations
import numpy as np

# Machine Learning
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Deep Learning
import tensorflow as tf
from tensorflow import keras

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Time Series / Statistical modelling
import statsmodels.api as sm

# Interactive visualization
import plotly.express as px
import plotly.graph_objects as go

print("All libraries imported successfully ✅")

All libraries imported successfully ✅

In [3]:
df = pd.read_csv("/content/building_energy_800k.csv")
df.head()

,timestamp,electricity,chilled_water,steam,hot_water,gas,water,temperature,humidity
0,2016-01-01 00:00:00,63.394,48.528,21.342,18.743,14.282,6.803,12.56,36.76
1,2016-01-01 01:00:00,47.025,32.197,17.469,18.358,12.309,6.189,23.68,85.43
2,2016-01-01 02:00:00,55.048,41.767,27.018,15.952,13.382,8.331,24.75,37.80
3,2016-01-01 03:00:00,56.905,40.457,27.242,12.251,12.037,7.641,-9.13,100.00
4,2016-01-01 04:00:00,43.597,47.617,21.106,20.305,11.327,6.907,13.36,65.29

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   timestamp      800000 non-null  object
 1   electricity    800000 non-null  float64
 2   chilled_water  800000 non-null  float64
 3   steam          800000 non-null  float64
 4   hot_water      800000 non-null  float64
 5   gas            800000 non-null  float64
 6   water          800000 non-null  float64
 7   temperature    800000 non-null  float64
 8   humidity       800000 non-null  float64
dtypes: float64(8), object(1)
memory usage: 54.9+ MB

In [5]:
df.shape

(800000, 9)

In [6]:
df.columns

Index(['timestamp', 'electricity', 'chilled_water', 'steam', 'hot_water',
       'gas', 'water', 'temperature', 'humidity'],
      dtype='object')

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
 # Convert Timestamp to Datetime & Sort
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values('timestamp')

print("Timestamp converted & sorted ✅")

Timestamp converted & sorted ✅

In [9]:
# Handle Missing Values
df = df.fillna(method='ffill')  # forward fill
df = df.fillna(method='bfill')  # backward fill

print("Missing values handled ✅")

Missing values handled ✅

/tmp/ipython-input-2312990077.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')  # forward fill
/tmp/ipython-input-2312990077.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='bfill')  # backward fill

In [10]:
df.isnull().sum()

timestamp        0
electricity      0
chilled_water    0
steam            0
hot_water        0
gas              0
water            0
temperature      0
humidity         0
dtype: int64

In [11]:
# Cap Outliers (1%-99% Quantile)

# Explanation: Extreme values data ko distort kar sakte hain. 1% lowest aur 1% highest values cap kar dete hain.

for col in df.columns:
    if col != 'timestamp':
        lower = df[col].quantile(0.01)
        upper = df[col].quantile(0.99)
        df[col] = df[col].clip(lower, upper)

print("Outliers capped ✅")

Outliers capped ✅

In [12]:
# Normalize Numeric
numeric_cols = df.columns.drop('timestamp')  # all numeric columns except timestamp

scaler = MinMaxScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("Normalization done ✅")

# Explanation: ML algorithms ke liye numeric values ko 0–1 range me lana zaruri hai.

Normalization done ✅

In [13]:
# Final Check
df.isnull().sum()

timestamp        0
electricity      0
chilled_water    0
steam            0
hot_water        0
gas              0
water            0
temperature      0
humidity         0
dtype: int64

In [14]:
df.head()

,timestamp,electricity,chilled_water,steam,hot_water,gas,water,temperature,humidity
0,2016-01-01 00:00:00,0.515603,0.723469,0.306116,0.452321,0.595507,0.434026,0.382985,0.309532
1,2016-01-01 01:00:00,0.125967,0.145381,0.072042,0.422974,0.374986,0.305223,0.621304,0.840921
2,2016-01-01 02:00:00,0.316941,0.484142,0.649160,0.239576,0.494914,0.754563,0.644236,0.320887
3,2016-01-01 03:00:00,0.361144,0.437770,0.662698,0.000000,0.344585,0.609817,0.000000,1.000000
4,2016-01-01 04:00:00,0.044369,0.691221,0.291853,0.571385,0.265229,0.455842,0.400130,0.621028

In [15]:
df.describe()

,timestamp,electricity,chilled_water,steam,hot_water,gas,water,temperature,humidity
count,800000,800000.000000,800000.000000,800000.000000,800000.000000,800000.000000,800000.000000,800000.000000,800000.000000
mean,2061-08-18 15:29:59.999997440,0.413280,0.414188,0.413247,0.411434,0.414475,0.414203,0.499583,0.508420
min,2016-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2038-10-25 07:45:00,0.264597,0.265487,0.264656,0.263282,0.265117,0.265156,0.354909,0.361066
50%,2061-08-18 15:30:00,0.395277,0.396142,0.395262,0.393094,0.396558,0.396476,0.499358,0.508680
75%,2084-06-11 23:15:00,0.542644,0.543469,0.542548,0.539904,0.544540,0.543528,0.644236,0.656294
max,2107-04-07 07:00:00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,NaN,0.207292,0.207275,0.207016,0.206653,0.207947,0.207685,0.210760,0.214318

In [17]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.dtypes

#Convert Timestamp to Datetime

timestamp        datetime64[ns]
electricity             float64
chilled_water           float64
steam                   float64
hot_water               float64
gas                     float64
water                   float64
temperature             float64
humidity                float64
dtype: object

In [18]:
# feature engineering

# Rolling Statistics
# Rolling mean & rolling standard deviation (7-day window = 168 hours)
df['electricity_rolling_mean_168'] = df['electricity'].rolling(window=168).mean()
df['electricity_rolling_std_168'] = df['electricity'].rolling(window=168).std()
df['electricity_rolling_min_168'] = df['electricity'].rolling(window=168).min()
df['electricity_rolling_max_168'] = df['electricity'].rolling(window=168).max()

df[['electricity_rolling_mean_168','electricity_rolling_std_168']].tail()

# Rolling mean = pichle 7 din ka average, jo current value ko smooth karta hai.
# Rolling std = pichle 7 din ka variation, anomaly detect karne me madad karta hai.

        electricity_rolling_mean_168  electricity_rolling_std_168
799995                      0.411923                     0.213514
799996                      0.411678                     0.213900
799997                      0.412536                     0.214684
799998                      0.414451                     0.214418
799999                      0.414597                     0.214421

In [19]:
# Short-Term Rolling (24 Hours)
df['electricity_rolling_mean_24'] = df['electricity'].rolling(window=24).mean()
df['electricity_rolling_std_24'] = df['electricity'].rolling(window=24).std()

df[['electricity_rolling_mean_24','electricity_rolling_std_24']].tail()

        electricity_rolling_mean_24  electricity_rolling_std_24
799995                     0.426664                    0.201787
799996                     0.420361                    0.211052
799997                     0.430872                    0.217562
799998                     0.427196                    0.214725
799999                     0.408517                    0.191896

In [21]:
# Deviation from baseline
#Purpose: Current value ka comparison past trend se
df['electricity_deviation_168'] = (
    df['electricity'] - df['electricity_rolling_mean_168']
) / (df['electricity_rolling_std_168'] + 1e-5)

df['electricity_deviation_24'] = (
    df['electricity'] - df['electricity_rolling_mean_24']
) / (df['electricity_rolling_std_24'] + 1e-5)

df[['electricity_deviation_168','electricity_deviation_24']].tail()

#Deviation = (current - average) / std.
#Agar deviation zyada hai → unusual spike ya drop → anomaly detect kar sakte hain.

        electricity_deviation_168  electricity_deviation_24
799995                  -0.811929                 -0.932160
799996                  -1.657591                 -1.721091
799997                   1.240859                  1.140172
799998                   0.607602                  0.547385
799999                   0.080409                  0.121529

In [22]:
# Time-based features
df['hour'] = df['timestamp'].dt.hour
df['day_of_week'] = df['timestamp'].dt.dayofweek
df['day_of_month'] = df['timestamp'].dt.day
df['month'] = df['timestamp'].dt.month
df['week_of_year'] = df['timestamp'].dt.isocalendar().week.astype(int)
df['quarter'] = df['timestamp'].dt.quarter
df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)

df[['hour','day_of_week','month','is_weekend']].head()
#Purpose: Seasonality aur time-of-day/week pattern capture karna.

   hour  day_of_week  month  is_weekend
0     0            4      1           0
1     1            4      1           0
2     2            4      1           0
3     3            4      1           0
4     4            4      1           0

In [23]:
# Cyclical Encoding (Very Important)
df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

df[['hour_sin','hour_cos','month_sin','month_cos']].head()

   hour_sin  hour_cos  month_sin  month_cos
0  0.000000  1.000000        0.5   0.866025
1  0.258819  0.965926        0.5   0.866025
2  0.500000  0.866025        0.5   0.866025
3  0.707107  0.707107        0.5   0.866025
4  0.866025  0.500000        0.5   0.866025

In [24]:
# Lag Features
df['electricity_lag1'] = df['electricity'].shift(1)
df['electricity_lag3'] = df['electricity'].shift(3)
df['electricity_lag6'] = df['electricity'].shift(6)
df['electricity_lag24'] = df['electricity'].shift(24)
df['electricity_lag168'] = df['electricity'].shift(168)

df[['electricity_lag1','electricity_lag24']].tail()

# ag features → previous values ka reference, ML model future prediction ya anomaly detection me help karta hai.

        electricity_lag1  electricity_lag24
799995          0.186356           0.334127
799996          0.238557           0.208374
799997          0.057104           0.426674
799998          0.678941           0.632977
799999          0.544738           0.880127

In [25]:
# Consumption Ratios
df['ratio_to_24hr_mean'] = df['electricity'] / (df['electricity_rolling_mean_24'] + 1e-5)
df['ratio_to_7day_mean'] = df['electricity'] / (df['electricity_rolling_mean_168'] + 1e-5)

df[['ratio_to_24hr_mean','ratio_to_7day_mean']].tail()

        ratio_to_24hr_mean  ratio_to_7day_mean
799995            0.559107            0.579115
799996            0.135842            0.138707
799997            1.575700            1.645733
799998            1.275120            1.314328
799999            1.057064            1.041563

In [26]:
# Difference Features
df['diff_1hr'] = df['electricity'] - df['electricity_lag1']
df['diff_24hr'] = df['electricity'] - df['electricity_lag24']

df[['diff_1hr','diff_24hr']].tail()

        diff_1hr  diff_24hr
799995  0.052201  -0.095570
799996 -0.181452  -0.151270
799997  0.621837   0.252267
799998 -0.134203  -0.088239
799999 -0.112899  -0.448287

In [27]:
# Expanding Statistics
df['expanding_mean'] = df['electricity'].expanding().mean()
df['expanding_std'] = df['electricity'].expanding().std()

df[['expanding_mean','expanding_std']].tail()

        expanding_mean  expanding_std
799995        0.413279       0.207292
799996        0.413279       0.207292
799997        0.413279       0.207292
799998        0.413280       0.207292
799999        0.413280       0.207292

In [28]:
# FINAL STEP — Check Total Columns
print("Total Columns Now:", df.shape[1])

Total Columns Now: 39

In [32]:
# Optional — Fill NaN for rolling & lag
df = df.fillna(method='bfill')  # backward fill missing values

# Rolling mean/std aur lag se kuch NaN aayenge first rows me, unhe fill karna hai:

/tmp/ipython-input-3284614643.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='bfill')  # backward fill missing values

In [33]:
df = df.dropna()
print("After dropping NaN:", df.shape)

After dropping NaN: (799832, 39)

In [ ]:
# ✅ Presentation Notes (Explain Confidently)

# Rolling statistics smooth data aur variability detect karte hain.

# Deviation metric anomalies ko highlight karta hai.

# Time-based features seasonality aur periodic patterns capture karte hain.

# Lag features historical values ko include karke model ko trend aur momentum samjhate hain